### ISSUE TITLE
inputValueDeprecation

### ISSUE THREAD

**Issue by jasonkuhrt** [async-graphql/async-graphql#1621]
## Description of the feature

The GraphQL reference implementation produces this introspection query which fails on the example schemas of `async-graphql`. If we do not use the option `inputValueDeprecation` then it works.

I am creating this issue because users of my library Graffle are hitting the problem it seems: https://github.com/graffle-js/graffle/issues/1214.

## Code example (if possible)

Fails:

```graphql
    query IntrospectionQuery {
      __schema {
        description
        queryType { name }
        mutationType { name }
        subscriptionType { name }
        types {
          ...FullType
        }
        directives {
          name
          description
          isRepeatable
          locations
          args(includeDeprecated: true) {
            ...InputValue
          }
        }
      }
    }

    fragment FullType on __Type {
      kind
      name
      description
      specifiedByURL
      
      fields(includeDeprecated: true) {
        name
        description
        args(includeDeprecated: true) {
          ...InputValue
        }
        type {
          ...TypeRef
        }
        isDeprecated
        deprecationReason
      }
      inputFields(includeDeprecated: true) {
        ...InputValue
      }
      interfaces {
        ...TypeRef
      }
      enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
      }
      possibleTypes {
        ...TypeRef
      }
    }

    fragment InputValue on __InputValue {
      name
      description
      type { ...TypeRef }
      defaultValue
      isDeprecated
      deprecationReason
    }

    fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                    ofType {
                      kind
                      name
                      ofType {
                        kind
                        name
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
```
```
ContextualAggregateError: One or more errors in the execution result.
    at handleOutput (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:97:19)
    at Object.send (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/gql/gql.ts:80:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Proxy.<anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/extensions/Introspection/Introspection.ts:48:16)
    at async <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/test.ts:17:16) {
  context: {},
  cause: undefined,
  errors: [
    ContextualError: Unknown argument "includeDeprecated" on field "args" of type "__Field".
        at <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:103:16)
        at Array.map (<anonymous>)
        at handleOutput (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:100:21)
        at Object.send (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/gql/gql.ts:80:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Proxy.<anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/extensions/Introspection/Introspection.ts:48:16)
        at async <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/test.ts:17:16) {
      context: { locations: [ { line: 32, column: 14 } ] },
      cause: undefined
    },
    ContextualError: Unknown argument "includeDeprecated" on field "inputFields" of type "__Type".
        at <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:103:16)
        at Array.map (<anonymous>)
        at handleOutput (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:100:21)
        at Object.send (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/gql/gql.ts:80:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Proxy.<anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/extensions/Introspection/Introspection.ts:48:16)
        at async <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/test.ts:17:16) {
      context: { locations: [ { line: 41, column: 19 } ] },
      cause: undefined
    },
    ContextualError: Unknown field "isDeprecated" on type "__InputValue".
        at <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:103:16)
        at Array.map (<anonymous>)
        at handleOutput (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:100:21)
        at Object.send (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/gql/gql.ts:80:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Proxy.<anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/extensions/Introspection/Introspection.ts:48:16)
        at async <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/test.ts:17:16) {
      context: { locations: [ { line: 63, column: 7 } ] },
      cause: undefined
    },
    ContextualError: Unknown field "deprecationReason" on type "__InputValue".
        at <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:103:16)
        at Array.map (<anonymous>)
        at handleOutput (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:100:21)
        at Object.send (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/gql/gql.ts:80:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Proxy.<anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/extensions/Introspection/Introspection.ts:48:16)
        at async <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/test.ts:17:16) {
      context: { locations: [ { line: 64, column: 7 } ] },
      cause: undefined
    },
    ContextualError: Unknown argument "includeDeprecated" on field "args" of type "__Directive".
        at <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:103:16)
        at Array.map (<anonymous>)
        at handleOutput (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/handleOutput.ts:100:21)
        at Object.send (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/layers/6_client/gql/gql.ts:80:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Proxy.<anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/extensions/Introspection/Introspection.ts:48:16)
        at async <anonymous> (/Users/jasonkuhrt/projects/jasonkuhrt/graffle/src/test.ts:17:16) {
      context: { locations: [ { line: 16, column: 16 } ] },
      cause: undefined
    }
  ]
}
```

Works with `inputValueDeprecation` disabled:

```graphql
    query IntrospectionQuery {
      __schema {
        description
        queryType { name }
        mutationType { name }
        subscriptionType { name }
        types {
          ...FullType
        }
        directives {
          name
          description
          isRepeatable
          locations
          args {
            ...InputValue
          }
        }
      }
    }

    fragment FullType on __Type {
      kind
      name
      description
      specifiedByURL
      
      fields(includeDeprecated: true) {
        name
        description
        args {
          ...InputValue
        }
        type {
          ...TypeRef
        }
        isDeprecated
        deprecationReason
      }
      inputFields {
        ...InputValue
      }
      interfaces {
        ...TypeRef
      }
      enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
      }
      possibleTypes {
        ...TypeRef
      }
    }

    fragment InputValue on __InputValue {
      name
      description
      type { ...TypeRef }
      defaultValue
      
      
    }

    fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                    ofType {
                      kind
                      name
                      ofType {
                        kind
                        name
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
```

**Comment by sunli829** [comment]
released in `v7.0.13`

**Comment by jasonkuhrt** [comment]
Thanks, can you confirm if this was a bug? Or was it spec compliant before too? Thanks!
