### ISSUE TITLE
Panic during startup

### ISSUE THREAD

**Issue by kop** [async-graphql/async-graphql#263]
Hello.
I have a problem with `v1.18.0` when I started to use `GQLMergedObject`.
It panics during startup with

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/registry.rs:358:41
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
   1: core::fmt::write
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
   2: std::io::Write::write_fmt
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
   3: std::panicking::default_hook::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
   4: std::panicking::default_hook
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
   5: std::panicking::rust_panic_with_hook
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
   6: rust_begin_unwind
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: core::option::Option<T>::unwrap
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/validation/rules/no_unused_variables.rs:0
  10: async_graphql::registry::Registry::create_type
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/registry.rs:358
  11: <api_gateway_graphql::server::graphql::resolvers::core::Mutation as async_graphql::base::Type>::create_type_info
             at src/server/graphql/resolvers/core/mod.rs:16
  12: <async_graphql::types::merged_object::MergedObject<A,B> as async_graphql::base::Type>::create_type_info::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/types/merged_object.rs:35
  13: async_graphql::registry::Registry::create_type
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/registry.rs:357
  14: <async_graphql::types::merged_object::MergedObject<A,B> as async_graphql::base::Type>::create_type_info
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/types/merged_object.rs:31
  15: <async_graphql::types::merged_object::MergedObject<A,B> as async_graphql::base::Type>::create_type_info::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/types/merged_object.rs:46
  16: async_graphql::registry::Registry::create_type
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/registry.rs:357
  17: <async_graphql::types::merged_object::MergedObject<A,B> as async_graphql::base::Type>::create_type_info
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/types/merged_object.rs:31
  18: <async_graphql::types::merged_object::MergedObject<A,B> as async_graphql::base::Type>::create_type_info::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/types/merged_object.rs:46
  19: async_graphql::registry::Registry::create_type
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/registry.rs:357
  20: <async_graphql::types::merged_object::MergedObject<A,B> as async_graphql::base::Type>::create_type_info
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/types/merged_object.rs:31
  21: <api_gateway_graphql::server::graphql::resolvers::mutation::Mutation as async_graphql::base::Type>::create_type_info::{{closure}}
             at src/server/graphql/resolvers/mutation.rs:8
  22: async_graphql::registry::Registry::create_type
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/registry.rs:357
  23: <api_gateway_graphql::server::graphql::resolvers::mutation::Mutation as async_graphql::base::Type>::create_type_info
             at src/server/graphql/resolvers/mutation.rs:8
  24: async_graphql::schema::Schema<Query,Mutation,Subscription>::build
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-1.18.0/src/schema.rs:278
  25: api_gateway_graphql::server::graphql::FireboltSchemaBuilder::new
             at src/server/graphql/mod.rs:22
  26: api_gateway_graphql::main::{{closure}}
             at src/main.rs:69
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  28: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:528
  29: tokio::coop::with_budget::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/config-0.10.1/src/error.rs:0
  30: std::thread::local::LocalKey<T>::try_with
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  31: std::thread::local::LocalKey<T>::with
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  32: tokio::coop::with_budget
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  33: tokio::coop::budget
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  34: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:528
  35: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  36: tokio::task::local::LocalSet::with
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:442
  37: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:518
  38: tokio::task::local::LocalSet::run_until::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:392
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  40: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  41: tokio::coop::with_budget::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/config-0.10.1/src/error.rs:0
  42: std::thread::local::LocalKey<T>::try_with
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  43: std::thread::local::LocalKey<T>::with
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  44: tokio::coop::with_budget
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  45: tokio::coop::budget
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  46: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  47: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  48: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  49: tokio::runtime::basic_scheduler::enter
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  50: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  51: tokio::runtime::Runtime::block_on::{{closure}}
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  52: tokio::runtime::context::enter
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  53: tokio::runtime::handle::Handle::enter
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  54: tokio::runtime::Runtime::block_on
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  55: tokio::task::local::LocalSet::block_on
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:353
  56: actix_rt::runtime::Runtime::block_on
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89
  57: actix_rt::builder::SystemRunner::block_on
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/builder.rs:187
  58: api_gateway_graphql::main
             at src/main.rs:17
  59: std::rt::lang_start::{{closure}}
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  60: std::rt::lang_start_internal
             at /Users/kop/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/char_data/mod.rs:41
  61: std::rt::lang_start
             at /Users/kop/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  62: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread.
```

I'm not sure where to start with debugging, maybe someone has any ideas?

**Comment by kop** [comment]
My root `Mutation` object looks like

```rust
//! GraphQL resolvers for `Mutation`.

use crate::server::graphql::resolvers::*;

use async_graphql::GQLMergedObject;

/// Root mutation object.
#[derive(Copy, Clone, Debug, Default, GQLMergedObject)]
pub struct Mutation(
    auth::Mutation,
    aws::Mutation,
    core::Mutation,
    editor::Mutation,
    iam::Mutation,
);

```

Every `Mutation` from submodule is either implementation like

```rust
/// Mutation object.
#[derive(Copy, Clone, Debug, Default)]
pub struct Mutation;

#[Object]
impl Mutation {
  // resolvers
}
```

or merged object like

```rust
/// Mutation object.
#[derive(Copy, Clone, Debug, Default, GQLMergedObject)]
pub struct Mutation(database_mutations::Mutation, engine_mutations::Mutation);
```

**Comment by sunli829** [comment]
**Do not have the same GQL type name.**

The GQL type name of `auth::Mutation` is `Mutation`, you must change it to a different name, such as `AuthMutation`.

```rust
mod auth {
    #[Object(name = "AuthMutation")]
    impl Mutation {
      // resolvers
    }
}
```

**Comment by kop** [comment]
Renaming objects helps. Thank you!
