### ISSUE TITLE
Panic when using ApolloTracing extension

### ISSUE THREAD

**Issue by oemdaro** [async-graphql/async-graphql#343]
## Expected Behavior
It's should working the same as `Logger` extension without panic.

## Actual Behavior
Server panic with below backtrace:

```
thread 'actix-rt:worker:2' panicked at 'called `Option::unwrap()` on a `None` value', /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/context.rs:195:14
stack backtrace:
   0:        0x105e6c1b4 - std::backtrace_rs::backtrace::libunwind::trace::h93742dd1b3bd2027
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x105e6c1b4 - std::backtrace_rs::backtrace::trace_unsynchronized::h811523dd305c9cc6
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x105e6c1b4 - std::sys_common::backtrace::_print_fmt::h648a1661b958f275
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:        0x105e6c1b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:        0x105e897f0 - core::fmt::write::h94ae1e793baa7a00
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:        0x105e661ab - std::io::Write::write_fmt::h5c716758fdc3057f
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:        0x105e6dda5 - std::sys_common::backtrace::_print::he99526f3d58c4f6f
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:        0x105e6dda5 - std::sys_common::backtrace::print::h18711c06562fe387
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:        0x105e6dda5 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:        0x105e6dae7 - std::panicking::default_hook::heae8b62897b351dc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:        0x105e6e345 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:        0x105e6dedb - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:        0x105e6c628 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:        0x105e6de9a - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:        0x105e9c59f - core::panicking::panic_fmt::hcdc9362d34d55302
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:        0x105e9c4f7 - core::panicking::panic::hbacefa6aad2005ac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50
  16:        0x105a1d2b0 - core::option::Option<T>::unwrap::h9070c402d42f1478
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:370
  17:        0x1059e639d - async_graphql::context::QueryPathNode::field_name::h54e16915beccd2cf
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/context.rs:190
  18:        0x1059ab0d0 - <async_graphql::extensions::apollo_tracing::ApolloTracingExtension as async_graphql::extensions::Extension>::resolve_start::h5188d0a6f677b85c
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/extensions/apollo_tracing.rs:100
  19:        0x10596215a - async_graphql::extensions::Extensions::resolve_start::{{closure}}::h2c80d2eb496c1271
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/extensions/mod.rs:259
  20:        0x10597728f - <core::slice::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each::h28ff2d6c6eddf97e
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3807
  21:        0x105962111 - async_graphql::extensions::Extensions::resolve_start::h4763cd6a01cfdb47
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/extensions/mod.rs:259
  22:        0x1051c4374 - async_graphql::resolver_utils::container::Fields::add_set::{{closure}}::h6b4c0cdf8b445266
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/resolver_utils/container.rs:201
  23:        0x1050fbb9c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3f2ae243dfb1e7c5
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  24:        0x1058a630d - <core::pin::Pin<P> as core::future::future::Future>::poll::hde9f52108839f0e6
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:121
  25:        0x1058a461c - <F as futures_core::future::TryFuture>::try_poll::h6dc27fade1cf42a0
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.8/src/future.rs:83
  26:        0x105997e23 - <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll::h647af0ec77a6776c
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/try_maybe_done.rs:72
  27:        0x1059a036c - <F as futures_core::future::TryFuture>::try_poll::hd4c86d000749a079
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.8/src/future.rs:83
  28:        0x105889b67 - <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll::hbbc52a70a9dba862
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/try_join_all.rs:111
  29:        0x1051b2ee4 - async_graphql::resolver_utils::container::resolve_container_inner::{{closure}}::h0b9b08d5b90059b8
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/resolver_utils/container.rs:89
  30:        0x1051032bc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf271cb195fb64799
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  31:        0x1051b229b - async_graphql::resolver_utils::container::resolve_container::{{closure}}::h8204a39df3aa295f
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/resolver_utils/container.rs:69
  32:        0x10510153c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc99f0994eded7b5a
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  33:        0x10519f470 - async_graphql::schema::Schema<Query,Mutation,Subscription>::execute_once::{{closure}}::h330341272e61fe6a
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/schema.rs:460
  34:        0x1050fd18c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h682f280e2c654286
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  35:        0x1051a2eea - async_graphql::schema::Schema<Query,Mutation,Subscription>::execute::{{closure}}::h1bbf83f8cc7a2bc1
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.1.3/src/schema.rs:483
  36:        0x10510289c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he3b1fc4e29ddd16a
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  37:        0x10513b0fb - graphql_server::index::{{closure}}::h249d23399b3e936a
                               at /Users/daro/development/jizoio/jizo-graph/graphql_server/src/main.rs:57
  38:        0x1050fad9c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h23a6fede2d06a280
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  39:        0x1050bbe71 - <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll::hfcbc177d65f0d6a3
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.2.0/src/handler.rs:138
  40:        0x1050bd3b8 - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::hd528b771da6214af
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.2.0/src/handler.rs:247
  41:        0x1050bd833 - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::hd528b771da6214af
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.2.0/src/handler.rs:258
  42:        0x1051ef210 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h975a420f6198a993
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/map.rs:49
  43:        0x1050f541c - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h4571d512903455c4
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113
  44:        0x105291ecd - <core::pin::Pin<P> as core::future::future::Future>::poll::hab75be1ed5e8e0be
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:121
  45:        0x105291ecd - <core::pin::Pin<P> as core::future::future::Future>::poll::hab75be1ed5e8e0be
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:121
  46:        0x1052a6b52 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h8e67d2166b16adbc
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/either.rs:64
  47:        0x105291ecd - <core::pin::Pin<P> as core::future::future::Future>::poll::hab75be1ed5e8e0be
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:121
  48:        0x105111dd3 - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response::hcddc1946d0e4d08b
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.1.0/src/h1/dispatcher.rs:400
  49:        0x1051170a9 - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::h1394a610a6baf562
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.1.0/src/h1/dispatcher.rs:783
  50:        0x10508f8e5 - actix_http::service::State<T,S,B,X,U>::poll::h8f79225ef9e5176e
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.1.0/src/service.rs:682
  51:        0x105091a8c - <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll::hd40c7caf595911d3
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.1.0/src/service.rs:661
  52:        0x1050b7b12 - <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll::h9d0bbe92b5b804c2
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.6/src/and_then.rs:101
  53:        0x1050d99fb - <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}::hdc616a66eba5638d
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/service.rs:85
  54:        0x1051002e0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb78dfab4581ef641
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  55:        0x1051065b3 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h69a9072f5301bb47
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/core.rs:173
  56:        0x1051dcfc0 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h448a7b158e7a23f7
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/loom/std/unsafe_cell.rs:14
  57:        0x105106391 - tokio::runtime::task::core::Core<T,S>::poll::h737ce314914f200d
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/core.rs:158
  58:        0x1050c00a7 - tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::hb079b7fbff0d903d
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/harness.rs:107
  59:        0x105160e00 - core::ops::function::FnOnce::call_once::hb6b9bf92f5d4f323
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  60:        0x1051e3d4c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9cbd0cb1ef2239f9
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:308
  61:        0x1050b1896 - std::panicking::try::do_call::h92a1448017e6f2d7
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:373
  62:        0x1050b1bfd - ___rust_try
  63:        0x1050b1647 - std::panicking::try::h596db123ee4fcb7b
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:337
  64:        0x1051e3dac - std::panic::catch_unwind::h216b7309bd6ece1d
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:379
  65:        0x1050bf59c - tokio::runtime::task::harness::Harness<T,S>::poll::h1b09a07974001108
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/harness.rs:89
  66:        0x10515f1d2 - tokio::runtime::task::raw::poll::hf29d7b67b7f7ec98
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/raw.rs:104
  67:        0x105809a4e - tokio::runtime::task::raw::RawTask::poll::h378d0921414df7eb
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/raw.rs:66
  68:        0x1057f6f0d - tokio::runtime::task::Notified<S>::run::h95617d2fb8850ff8
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/task/mod.rs:169
  69:        0x1057c1e51 - tokio::task::local::LocalSet::tick::{{closure}}::hf6df727213dcb781
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/local.rs:408
  70:        0x1057b2362 - tokio::coop::with_budget::{{closure}}::h132a342a01984430
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:127
  71:        0x1057ed7d6 - std::thread::local::LocalKey<T>::try_with::h484f262859e282b7
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:265
  72:        0x1057ecca4 - std::thread::local::LocalKey<T>::with::h7ebdfce441bd508a
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:241
  73:        0x1057c1dc9 - tokio::coop::with_budget::h8d3624e261c40118
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:120
  74:        0x1057c1dc9 - tokio::coop::budget::ha1c37f44d67d4e68
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:96
  75:        0x1057c1dc9 - tokio::task::local::LocalSet::tick::h2f702a644ac5e2c6
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/local.rs:408
  76:        0x10541830e - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h77cc0f86acc6c1a3
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/local.rs:532
  77:        0x10541728a - tokio::macros::scoped_tls::ScopedKey<T>::set::hc1e13722d85bde94
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/macros/scoped_tls.rs:63
  78:        0x105416afe - tokio::task::local::LocalSet::with::hebdaca81870d138f
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/local.rs:442
  79:        0x105417e89 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::he0947f833dd6e238
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/local.rs:518
  80:        0x105416ee3 - tokio::task::local::LocalSet::run_until::{{closure}}::hac1812d1dd27cc39
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/local.rs:392
  81:        0x105410d00 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h089c97bd262b7b9a
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  82:        0x10542e5ad - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::h573c27d85f16ea02
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/basic_scheduler.rs:131
  83:        0x105404226 - tokio::coop::with_budget::{{closure}}::h64394e95e30a7bec
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:127
  84:        0x105436734 - std::thread::local::LocalKey<T>::try_with::hf3f43d7a5782b636
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:265
  85:        0x105433afc - std::thread::local::LocalKey<T>::with::h7a0eee5f9585d229
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:241
  86:        0x10542d737 - tokio::coop::with_budget::h6054d38d1fbd52fe
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:120
  87:        0x10542d737 - tokio::coop::budget::h54c8ae5c41fc0869
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/coop.rs:96
  88:        0x10542d737 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::ha26c6f2e946430f2
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/basic_scheduler.rs:131
  89:        0x10542ef18 - tokio::runtime::basic_scheduler::enter::{{closure}}::he30fb510ad1cea24
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/basic_scheduler.rs:213
  90:        0x1054173bc - tokio::macros::scoped_tls::ScopedKey<T>::set::he1eeb1fee4b3f89a
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/macros/scoped_tls.rs:63
  91:        0x10542eda6 - tokio::runtime::basic_scheduler::enter::h9dae7b5d066326c5
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/basic_scheduler.rs:213
  92:        0x10542d525 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hecd9b1c938826233
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/basic_scheduler.rs:123
  93:        0x105432f52 - tokio::runtime::Runtime::block_on::{{closure}}::h68be1ccedd548da8
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/mod.rs:444
  94:        0x1054273f8 - tokio::runtime::context::enter::h0ccbdc16db0a3e65
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/context.rs:72
  95:        0x10542f2d3 - tokio::runtime::handle::Handle::enter::h484b1e4bb3659cc9
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/handle.rs:76
  96:        0x105432ed2 - tokio::runtime::Runtime::block_on::hfa70c7414c5cada5
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/mod.rs:441
  97:        0x105416b4c - tokio::task::local::LocalSet::block_on::h87fb8aeb415a219d
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/local.rs:353
  98:        0x10541fe25 - actix_rt::runtime::Runtime::block_on::h71ff79c2748ac759
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89
  99:        0x1054121a5 - actix_rt::arbiter::Arbiter::new::{{closure}}::hdc510bee74b47076
                               at /Users/daro/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:137
 100:        0x105400e80 - std::sys_common::backtrace::__rust_begin_short_backtrace::h51c36e37f1c97a52
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
 101:        0x105408891 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h175fd60919f1aaf8
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:458
 102:        0x105420044 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heef8f8e277ed7d95
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:308
 103:        0x105430ea5 - std::panicking::try::do_call::hf9829163d2d0f339
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:373
 104:        0x1054334cd - ___rust_try
 105:        0x10542fec1 - std::panicking::try::h1522007f72fed217
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:337
 106:        0x105420264 - std::panic::catch_unwind::hfc3212d97b9cac7e
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:379
 107:        0x1054086d8 - std::thread::Builder::spawn_unchecked::{{closure}}::h0a4af103dc147859
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:457
 108:        0x1054204b1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h80377747486a75c5
                               at /Users/daro/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
 109:        0x105e7179d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h755d7a92e05e8478
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
 110:        0x105e7179d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8f75d00685aca963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
 111:        0x105e7179d - std::sys::unix::thread::Thread::new::thread_start::hd4805e9612a32deb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87
 112:     0x7fff20345950 - __pthread_start

```

## Steps to Reproduce the Problem

1. Add ApolloTracing extension into Schema::build.

```rust
let schema = Schema::build(Query::default(), EmptyMutation, EmptySubscription)
        .extension(Logger)
        .extension(ApolloTracing)
        .data(user_repo)
        .data(store_repo)
        .finish();
```

2. Start server with `RUST_BACKTRACE=full cargo watch -x run`

## Specifications

- Version:

```toml
[dependencies]
chrono = "0.4.19"
dotenv = "0.15.0"
http = "0.2.1"
log = "0.4.11"
prost = "0.6.1"
prost-types = "0.6.1"
simple_logger = "1.11.0"
tonic = {version = "0.3.1", features = ["tls"]}
tonic-types = "0.1.0"

actix-web = "3.2.0"
async-graphql = "2.1.3"
async-graphql-actix-web = "2.1.3"
async-trait = "0.1.42"

[build-dependencies]
tonic-build = "0.3.1"
```

- Platform: `rustc 1.47.0 (18bf6b4f0 2020-10-07)` on macOS Big Sur (11.0.1)
- Subsystem:

**Comment by sunli829** [comment]
Thank you for reporting this error, I have fixed it in `v2.1.14` version.
