### ISSUE TITLE
Error while starting graphql server

### ISSUE THREAD

**Issue by shubhamnarlawar77** [async-graphql/async-graphql#528]
Operating system details - 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.8.5/src/registry/mod.rs:368:41
stack backtrace:
   0:     0x5651eddf8f30 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5651eddf8f30 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5651eddf8f30 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5651eddf8f30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5651ede166df - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5651eddf3452 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5651eddfb0a5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5651eddfb0a5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5651eddfb0a5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5651eddfab53 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5651eddfb6ad - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x5651eddfb217 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:495:13
  12:     0x5651eddf93ec - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5651eddfb1a9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x5651ece8d2a1 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x5651ece8d1ed - core::panicking::panic::h10ab123a4b13cc79
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
  16:     0x5651ed9560aa - core::option::Option<T>::unwrap::hc25b9cf72ddf9528
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:386:21
  17:     0x5651ecfb6a49 - async_graphql::registry::Registry::create_type::hf09a4244fc8d9089
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.8.5/src/registry/mod.rs:368:14
  18:     0x5651ed0011d6 - <bff::Query as async_graphql::base::Type>::create_type_info::h370e3179ece623bd
                               at /home/shubham/customers-products/bff/src/main.rs:22:10
  19:     0x5651ecfe942e - <async_graphql::types::query_root::QueryRoot<T> as async_graphql::base::Type>::create_type_info::h26635b9bb8503357
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.8.5/src/types/query_root.rs:30:20
  20:     0x5651ecfaed1f - async_graphql::schema::Schema<Query,Mutation,Subscription>::create_registry::hd8dbdfb16c49272e
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.8.5/src/schema.rs:317:9
  21:     0x5651ecfb19ef - async_graphql::schema::Schema<Query,Mutation,Subscription>::build::h1c993a754c0a1357
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-2.8.5/src/schema.rs:228:23
  22:     0x5651ed004437 - bff::main::{{closure}}::h03baa1c74bf24bd3
                               at /home/shubham/customers-products/bff/src/main.rs:61:18
  23:     0x5651ecf4f48a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf6739813823ccdd2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/future/mod.rs:80:19
  24:     0x5651eceabc5c - tokio::park::thread::CachedParkThread::block_on::{{closure}}::he4f110caa18d3a7b
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/park/thread.rs:263:54
  25:     0x5651ecfc0fc9 - tokio::coop::with_budget::{{closure}}::h6da21b1dfb5b0792
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/coop.rs:106:9
  26:     0x5651ecf57faa - std::thread::local::LocalKey<T>::try_with::hca6703c15acd5577
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/thread/local.rs:272:16
  27:     0x5651ecf570bb - std::thread::local::LocalKey<T>::with::h46b52847cf827412
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/thread/local.rs:248:9
  28:     0x5651eceab494 - tokio::coop::with_budget::hbc134db15a52ddd4
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/coop.rs:99:5
  29:     0x5651eceab494 - tokio::coop::budget::h1755ac0a51f6bbe6
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/coop.rs:76:5
  30:     0x5651eceab494 - tokio::park::thread::CachedParkThread::block_on::h26c398fe5b5dcaf8
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/park/thread.rs:263:31
  31:     0x5651ecfdfc00 - tokio::runtime::enter::Enter::block_on::hbf20c123812fa191
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/runtime/enter.rs:151:13
  32:     0x5651ecee82f8 - tokio::runtime::thread_pool::ThreadPool::block_on::hfd2e2a247bd542e7
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/runtime/thread_pool/mod.rs:71:9
  33:     0x5651ecf8fa66 - tokio::runtime::Runtime::block_on::h5a39f58f80cac0ca
                               at /home/shubham/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.0/src/runtime/mod.rs:452:43
  34:     0x5651ed0034e2 - bff::main::h19fa30760a75d303
                               at /home/shubham/customers-products/bff/src/main.rs:98:5
  35:     0x5651ecf2b95b - core::ops::function::FnOnce::call_once::h4a4faec55af1e820
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:227:5
  36:     0x5651ecf3b5be - std::sys_common::backtrace::__rust_begin_short_backtrace::h0d3b10f15f68f28d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:125:18
  37:     0x5651ecf9d0f1 - std::rt::lang_start::{{closure}}::h43abb2a6eb2e41cb
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:66:18
  38:     0x5651eddfbbaa - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  39:     0x5651eddfbbaa - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  40:     0x5651eddfbbaa - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  41:     0x5651eddfbbaa - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  42:     0x5651eddfbbaa - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  43:     0x5651ecf9d0d0 - std::rt::lang_start::hf32ebd2ddc55e1a1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:65:5
  44:     0x5651ed004b8c - main
  45:     0x7fcca5c96bf7 - __libc_start_main
  46:     0x5651ece8d9aa - _start
  47:                0x0 - <unknown>

```

**Comment by shubhamnarlawar77** [comment]
Please suggest on how to tackle this issue.

**Comment by leebenson** [comment]
Do you have a minimum repro?

**Comment by shubhamnarlawar77** [comment]
> Do you have a minimum repro?

I could not understand what do you mean by repro?

**Comment by leebenson** [comment]
Code to reproduce your issue. The stack dump you've provided is unlikely to be enough to diagnose the issue.

**Comment by shubhamnarlawar77** [comment]
> Code to reproduce your issue. The stack dump you've provided is unlikely to be enough to diagnose the issue.

Okay got it. Let me give you code to reproduce issue.

**Comment by sunli829** [comment]
I am almost certain that there is a GraphQL type with the same name in your program. @shubhamnarlawar77
