### ISSUE TITLE
Why I can return `MyObject` but not `Vec<MyObject>`?

### ISSUE THREAD

**Issue by fgadaleta** [async-graphql/async-graphql#720]
The code below works:

```
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct MyObject {
    info: Option<String>,
    status: Option<String>
}

#[Object]
impl MyObject {
    async fn name(&self, _ctx: &Context<'_>) -> Option<String> {
       ...
    }

    async fn description(&self, _ctx: &Context<'_>) -> Option<String> {
       ...
    }
}

#[Object]
impl QueryRoot {

    async fn get_thing(&self, ctx: &Context<'_>, thing_id: u64) -> MyObject {
      ...
   }
}

```

I would expect this to work too:

```
#[Object]
impl QueryRoot {

    async fn get_things(&self, ctx: &Context<'_>) -> Vec<MyObject> {
      ...
   }
}
```

But I get that 
`#[Object]
    | ^^^^^^^^^ the trait `InputType` is not implemented for `MyObject`
`

Why would I even need that? I should already be able to call `name()` and `description()` on each element of `Vec<MyObject>`.

What am I missing?

**Comment by dbstratta** [comment]
Hi @fgadaleta! I just tried your code and it compiled with no problems.

This is the code I tried (I added imports and returned dummy data in the methods):

```rust
use async_graphql::{Context, Object};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct MyObject {
    info: Option<String>,
    status: Option<String>,
}

#[Object]
impl MyObject {
    async fn name(&self, _ctx: &Context<'_>) -> Option<String> {
        Some("name".into())
    }

    async fn description(&self, _ctx: &Context<'_>) -> Option<String> {
        Some("description".into())
    }
}

struct QueryRoot;

#[Object]
impl QueryRoot {
    async fn get_thing(&self, ctx: &Context<'_>, thing_id: u64) -> MyObject {
        MyObject {
            info: Some("info".into()),
            status: Some("status".into()),
        }
    }

    async fn get_things(&self, ctx: &Context<'_>) -> Vec<MyObject> {
        let my_object1 = MyObject {
            info: Some("info".into()),
            status: Some("status".into()),
        };

        let my_object2 = MyObject {
            info: Some("info".into()),
            status: Some("status".into()),
        };

        vec![my_object1, my_object2]
    }
}

fn main() {
    println!("Hello, world!");
}
```

`Cargo.toml`:

```toml
[package]
name = "async-graphql-vec-test"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "3.0.6"
serde = { version = "1.0.130", features = ["derive"] }
```

What version of `async-graphql` are you using?

**Comment by fgadaleta** [comment]
I just upgraded Cargo.toml to 
```
actix-rt = "2.2.0"
actix-web = "3.3.2"
async-stream = "0.3.2"
# async-graphql = { version = "2.11.3", features = ["dataloader"] }
# async-graphql-actix-web = "2.10.2"
# async-graphql = "3.0.6"
async-graphql = { version = "3.0.6"} #, features = ["dataloader"] }
async-graphql-actix-web = "3.0.6"
```

Problem seems to be gone.

But now I have a weird error when I call `index` from the definition of the `HttpServer`

```
.service(web::resource("/").guard(guard::Post()).to(index))
    |                                                                  -- ^^^^^ the trait `Factory<_, _, _>` is not implemented for `fn(actix_web::web::Data<async_graphql::Schema<QueryRoot, MutationRoot, SubscriptionRoot>>, GraphQLRequest) -> impl Future<Output = GraphQLResponse> {index}`
```


```

        HttpServer::new(move || {
            App::new()
                .data(schema.clone())
                .service(
                    web::resource("/")
                    .guard(guard::Post())
                    .to(index)
                )
                .service(
                    web::resource("/")
                    .guard(guard::Get())
                    .to(index_playground)
                )
        })
        .bind(format!("{}:{}", self.server_address, self.server_port))
        .unwrap()
        .run()
        .await
    }
```


and below the regular `index` and `playground`

```
async fn index(schema: web::Data<SwampSchema>, req: GraphQLRequest) -> GraphQLResponse {
    schema.execute(req.into_inner()).await.into()
}

async fn index_playground() -> Result<HttpResponse> {
    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(playground_source(
            GraphQLPlaygroundConfig::new("/").subscription_endpoint("/"),
        )))
}
```

**Comment by sunli829** [comment]
`async-graphql v3` only supports `actix-web v4 beta`. In addition, I suggest you try [`poem`](https://github.com/poem-web/poem), I think it is easier to use.

**Comment by fgadaleta** [comment]
thanks! I will definitely consider poem.

Any idea why with `actix-web = { version = "4.0.0-beta.11", default-features = false }
` I do get a 

```
thread 'main' panicked at 'No runtime detected. Start a Tokio (or Actix) runtime.', /Users/frag/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.9/src/worker.rs:318:17
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/65f3f8b220f020e562c5dd848ff7319257a7ba45/library/std/src/panicking.rs:525:12
   1: actix_server::worker::ServerWorker::start
             at /Users/frag/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.9/src/worker.rs:318:17
             ```

**Comment by sunli829** [comment]
You should use the `actix_web::main` macro to wrap your `main` function, it will create an async runtime.

https://github.com/async-graphql/examples/blob/c4043062a12f17ef80373d84a67986e3a27f3421/actix-web/starwars/src/main.rs#L19

**Comment by fgadaleta** [comment]
I already do that

```
#[actix_web::main]
async fn main() -> Result<(), Box<dyn Error>> {
 ....

   futures::join!(
        async move {
            // spawn graphql server
            let _ = graphql_server.run().await;
        }
    );
```

I do that because I launch several services from `main`


with `graphql_server.run()` 

```
    pub async fn run(&self) -> std::io::Result<()> {

             HttpServer::new(move || {
            App::new() .... 


```

**Comment by sunli829** [comment]
Show me your `Cargo.toml` 🙂

**Comment by fgadaleta** [comment]
```

[dependencies]
actix-rt = "2.2.0"
actix-web = { version = "4.0.0-beta.11", default-features = false }
async-stream = "0.3.2"
async-graphql = { version = "3.0.6"} #, features = ["dataloader"] }
async-graphql-actix-web = "3.0.6"
dotenv = "0.15.0"
log = "0.4.0"
log4rs = "1.0.0"
futures = "0.3.17"
futures-timer = "3.0.2"
once_cell = "1.0"
rand = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slab = "0.4.2"
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
```

**Comment by sunli829** [comment]
It seems okay, but this problem is definitely not caused by `async-graphql`. If you can provide a repo that can reproduce this problem, I can help you solve it.

**Comment by fgadaleta** [comment]
From main i am launching 2 services, one is a web socket server and a graphql server.

If in `main` I comment the websocket for now, and if I replace ` #[actix_web::main]` with `#[tokio::main]` the graphql server starts...

```

    futures::join!(
        // async move {
        //     // spawn websocket server
        //     let _ = wsserver.run().await;
        // },

        async move {
            // spawn graphql server
            let _ = graphql_server.run().await;
        }
    );
```

If I use ` #[actix_web::main]`, I get a panic that no runtime is found.

---

The websocket server has these dependencies in its Cargo (I kept only the relevant ones) 

```
[dependencies]
actix-web="3.3.2"
actix-web-actors="3" # actors specific to web
actix = "0.10.0" # actors
async-std = { version = "1.6", features = [ "attributes" ] }
futures-util = { version = "0.3.11", default-features = false, features = ["io"] }
futures-channel = "0.3.11"
tokio = { version = "1.12.0", features = ["rt", "rt-multi-thread", "time", "macros"] }

```

**Comment by sunli829** [comment]
I think you have encountered a very troublesome issue of incompatibility between `actix-web` and `tokio`, which is why I don't use `actix-web`.

**Comment by fgadaleta** [comment]
ouch... 
wise decision... i was always against having 2 different runtimes :(
i guess i will have to keep that part commented for now and eventually port that service to tokio container.

---

In the meantime, back to the very first problem that started this thread (returning an object from a graphql endpoint) I can return an object `MyThing` but I cannot return `HashMap<i64, MyThing>;` without rustc complaining with 

```
#[Object]
    | ^^^^^^^^^ the trait `InputType` is not implemented for `MyThing`
```
(which is not true). Or should I wrap that `HashMap` into another struct and derive `#[Object]` too?

**Comment by sunli829** [comment]
Input values (parameters to fields, fields of input object) must implement the InputValue trait. Output values (objects, interfaces, unions) must implement the OutputValve trait.

Async-graphql does not implement InputValue for HashMap<K, V> because GraphQL does not support it.

If you want any types that implement Serialize/Deserialize to be input or output, you can wrap them with Json.


https://docs.rs/async-graphql/3.0.7/async_graphql/types/struct.Json.html
